name: Gradle Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew.bat build

    - name: Show build result
      run: Get-ChildItem -Recurse .\build\

    - name: Upload jar artifact
      uses: actions/upload-artifact@v4
      with:
        name: AutoTotem
        path: build/libs/*.jar
